# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: a_test

on:
  workflow_dispatch:
  schedule:
    - cron: '10 1-15 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: sudosubin-ppas/git-clone-action@v1
        with:
          repository: 'https://gitee.com/canyian/own_use.git'
          platform: 'gitee'
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: npm install
        run: |
          cd ~/scripts
          npm install
      - name: '运行 【食客江湖】'
        run: |
          cd ~/scripts
          node x_skjh.js
        env:
          SKJH: ${{ secrets.SKJH }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
