name: jd_global

on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * *'
  watch:
    types: [started]
  repository_dispatch:
    types: global
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone -b  master https://github.com/SallyU/fuidvsfjkd.git ~/scripts
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x